### ISSUE TITLE
No backup of Private keys?

### ISSUE THREAD

**Issue by dhammel** [Secure-File-Manager/Secure-File-Manager#19]
Hi,

as the warning said during app setup, if you uninstall app, can no longer decrypt files.

Upon reading faq, seems like its using strong encryption, however I find this below sort of beats it. 

First, i cant just backup data and know I can access them from a different device because the keys are stored on the originating device.
I would believe it be best to derive them from a user chosen password, so encrypted files need to be encrypted/decrypted by password, to avoid this issue.

Having root access, or any exploits within android itself could potentially bypass this app altogether where it wouldn't with some other encryption apps like s.s.e. (and if above is not addressed to avoid this issue, maybe a warning or root check alerting rooted users that the app is near pointless on rooted devices.)

Have you though of implementing at least a different mode, something like password-derived keys, as a 2nd option at least? 

The only advantage I see out of current method is ease of use, and maybe better brute-force resistance for the users who otherwise would choose bad passwords.

Im not exactly sure what your focus was when initially creating this app, but personally as of now there would be no point of encrypting my files with this app vs not having one at all.

Let me know what you think though.

Thank you!

**Comment by Alfavio** [comment]
Hi @dhammel! Thank you for creating this issue and made constructive criticism. Also thank you for your time that you gave to this app. I appreciate it!

> Im not exactly sure what your focus was when initially creating this app...

I build this app on pillars of security, usability, and privacy. I choose [`androidx.security.crypto`](https://developer.android.com/jetpack/androidx/releases/security) library to implement encryption in this app because of:

- Strong security that balances great encryption and good performance.
- It uses cryptographic primitives.
- It has native support by Google.
- Faster encrypt/decrypt files than [`CipherOutputStream`](https://developer.android.com/reference/javax/crypto/CipherOutputStream)/[`CipherInputStream` ](https://developer.android.com/reference/javax/crypto/CipherInputStream) _(like password-based encryption)_.
- It is user-friendly _(passwordless encryption)_.
- Keys are stored at the Android keystore system. 

If you are more curious:
 - [Article: Data encryption on Android with Jetpack Security.](https://medium.com/androiddevelopers/data-encryption-on-android-with-jetpack-security-e4cb0b2d2a9)
 - [Documentation: Work with data more securely](https://developer.android.com/topic/security/data.md)
 - [Documentation: Android keystore system](https://developer.android.com/training/articles/keystore)

**As a compromise between security and usability, I choose this way.** But you are correct. It is less secure than password-based encryption _(if the user uses strong passwords of course)_ because it is fragile to exploits and malware.

> Have you though of implementing at least a different mode, something like password-derived keys, as a 2nd option at least?

Yes. I plan to implement password-based encryption to mitigate this issue. I created #20 for this.

> ...maybe a warning or root check alerting rooted users that the app is near pointless on rooted devices

You are right. If someone has a rooted device, this app is useless. If someone rooting his device, he knows what is he doing. Because of that, I don't plan to add a root alert to the app. Also, it creates more complexity to the app and I want to keep this app as simple and little as possible to prevent bugs and security vulnerabilities. I added this topic to the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions/_edit#i-have-rooted-device-are-there-some-security-implications).

**Comment by dhammel** [comment]
@Alfavio I understabd your concern with not wantjng to bloat the code, reason I suggested a root alert is because there are many people who have a rooted device, not knowing it. Such as those buying used devices at places like ebay, or friends rooting their device thinkjng it may be best foe them for certain things...reasons of which the actual device owner may not know about, or its potential security concerns if device isn't managed right. Companies like comcast added a root warning in their apps (not blocking app though) for this actual reason. Maybe adding it in description instead though may be good enough.

Anyway, I will keep an eye on your project and if password-based encryption comes around, then It may suffice my needs.

Thanks for your reply, you can close this issue if you want

**Comment by Alfavio** [comment]
I understand. I added a warning about a rooted device to the app description. It is not the best way, but at least it's a compromise.
