### ISSUE TITLE
REQUEST_INSTALL_PACKAGES permission doesn't seem to fit in a file encryption app

### ISSUE THREAD

**Issue by blackandyellowgecko** [Secure-File-Manager/Secure-File-Manager#23]
This issue applies to version 0.1.4-beta

_REQUEST_INSTALL_PACKAGES_ permission makes sense in a file manager app, but not in a file encryption app. It's an unnecessary permission and it also can make the app not trustworthy.

**Comment by Alfavio** [comment]
Hi @blackandyellowgecko! Thank you, this is a good point. I removed the .apk installation feature and removed REQUEST_INSTALL_PACKAGES permission.

**Comment by fux0r2009** [comment]
Hello @blackandyellowgecko, I believe that this a mistake as this app is a secure file manager and not just an encryption app which means that removing this feature will limit a lot of users who are using this app exclusively as their file manager! and your argument is not sound since there is no trustworthiness gain by removing this feature since the app is OPEN SOURCE and the code is freely available to inspect! 

I hope this decision would be revised by the dev as it could affect many users who choose to rely on "Secure File Manager" and (as the name indicate) to manage their files.

Best regards
