### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by shouyou10** [Secure-File-Manager/Secure-File-Manager#3]
This app is not running when I am using Red Moon (an open source blue-light filter). As I use use Red Moon from dusk to dawn, will it be possible for me to run this app without turning off Red Moon?

**Comment by Alfavio** [comment]
Hi @shouyou10 . Thank you for the bug report! I appreciate that. I'm sorry you have this issue. The app is not working, because of the enabled [filterTouchesWhenObscured](https://developer.android.com/reference/android/view/View.html#attr_android:filterTouchesWhenObscured) flag. This flag prevents tapjacking attacks. If I disable this flag, the app will be vulnerable to tapjacking attacks, so I keep it enabled. Alternatively, you can use native night light mode, if your Android OS supports it. Eg, Lineage OS natively supports night light, and the app works if it is enabled. I added your question to the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#the-app-is-not-working-if-i-have-enabled-night-light-what-can-i-do).

**Comment by shouyou10** [comment]
Thank you for explaining it to me. If there is trade-off between app security and convenience, I will go with the security. Another question if I may ask is will it also not be possible to access SD card using this app?

**Comment by Alfavio** [comment]
This issue was already reported. I will fix it at soon as possible.

**Comment by Alfavio** [comment]
@shouyou10 It should be fixed in the new release. The new version will be soon available at Google Play and F-Droid.  Thank you for the bug report! If you have another bug report or feature request, please open a new issue.

More info: https://github.com/Secure-File-Manager/Secure-File-Manager/issues/1#issuecomment-786714278
