### ISSUE TITLE
Add FTP server,Root Explorer

### ISSUE THREAD

**Issue by coolerspeex** [Secure-File-Manager/Secure-File-Manager#5]
Add those both or you can get idea from another file manager like
https://github.com/zhanghai/MaterialFiles

Or if you can implement FTP server which we visit and looks a better modern design such as that below app does that will be awesome
https://play.google.com/store/apps/details?id=com.devaity.sendmate.paidOk

Thanks for this awesome file manager

**Comment by Alfavio** [comment]
Hi @coolerspeex. Thank you for the feature request! I appreciate that. 

Root explorer require a rooted device. The app is useless if the device is rooted because the majority of security features in the app will be vulnerable. Eg, all hidden files will be visible with root access. Because of that, I don't plan to add this feature to the app.

To share files, there are more secure protocols than FTP. Maybe integrate the [croc](https://github.com/schollz/croc) tool into the app will be a better way. Or use another end-to-end mechanism to share files between two devices. I created new issue #6  for this feature request.

If you have another feature request, please open a new issue.
